<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
موضوع‌بندی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
به یک تمرین صنعتی از  کاربرد یادگیری ماشین در پردازش زبان طبیعی (NLP) خوش آمدید.  در این تمرین داده‌های واقعی وب فارسی که توسط پلتفرم <a href="https://www.yektanet.com/">یکتانت</a> پالایش و جمع‌آوری شده در اختیار ما قرار گرفته است. هدف تمرین؛ ساخت یک مدل یادگیری ماشین است که با توجه متن‌های موجود در یک پیوند (Link) نظیر <i>عنوان</i>، <i>توضیحات</i>، <i>محتوای متنی [کامل]</i> و غیره بتواند دسته‌ی موضوعی آن سند را پیش‌بینی کند. به‌عنوان مثال اگر پیوندی از یک سایت خبری با عنوان «<i>کیهان کلهر جایزه مرد سال موسیقی جهان را دریافت کرد</i>» داشته باشیم، مدل ما باید پیش‌بینی کند که این مطلب مرتبط با موضوع «موسیقی» است. البته در این مثال ما تنها از ویژگی <i>عنوان</i> یاد کردیم، در حالی‌که می‌توان از متن <i>توضیحات</i> یا <i>محتوای متنی</i> هم کمک گرفت. 

</br>
توجه داشته باشید برای آن‌که بتوانید از الگوریتم‌های معرفی‌شده در کالج جهت کار روی داده‌های متنی استفاده کنید نیاز است حداقل با یکی از روش‌های تعبیه‌سازی (Embedding) آشنا شده باشید تا بتوانید هر متن را به یک بردار ویژگی عددی تبدیل کنید.

</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [2]:
import numpy as np
import pandas as pd

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    هر نمونه از این مجموعه‌داده با ویژگی‌هایی که در جدول زیر شرح داده شده همراه است. ستون <code>category</code> متغیر هدف مسئله است که موضوع محتوا را نشان می‌دهد. 
</font>
</p>
<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>category</code>| موضوع (متغیر هدف) |
|<code>description</code>| توضیحات |
|<code>text_content</code>| محتوای متنی |
|<code>title</code>| عنوان |
|<code>h1</code>| محتوای تگ <code>h1</code> صفحه |
|<code>h2</code>|محتوای تگ <code>h2</code> صفحه  |
|<code>url</code>| آدرس پیوند|
|<code>domain</code>|دامنه‌ی وب‌سایت |
|<code>id</code>|آیدی پیوند|

</font>
</div>
</center>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>yektanet_train.csv</code> و نمونه‌های آزمون که باید موضوع آن‌ها را پیش‌بینی کنید در فایل <code>yektanet_test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از مجموعه‌ی آموزشی را به عنوان مجموعه‌ی اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [74]:
train = pd.read_csv("../data/yektanet_train.csv")

train.head()

,category,description,text_content,title,h1,h2,url,domain,id
0,کتاب و ادبیات,"از شوبنده ها: جستجو معنی ""از شوبنده ها"" در فره...",معنی از شوبنده ها | جدول یاب از شوبنده ها 381,معنی از شوبنده ها | جدول یاب,معنی از شوبنده ها,از شوبنده ها در معادل ابجد,jadvalyab.ir/search?q=%D8%A7%D8%B2+%D8%B4%D9%8...,jadvalyab.ir,158
1,تجارت و اقتصاد,بیت‌کوین کش یک ارز مجازی مشهور است و بیت‌کوین ...,عکس بیت‌کوین کش برای پروفایل عکس و والپیپرهای ...,عکس بیت‌کوین کش برای پروفایل,عکس بیت‌کوین کش برای پروفایل,عکس بیت کوین با کیفیت 4K عکس ارزهای دیجیتال عک...,jowhareh.com/photo/%D8%B9%DA%A9%D8%B3-%D8%A8%D...,jowhareh.com,3268
2,سلامت,نوبت دهی دکتر مهناز عابدینی متخصص رادیولوژی و ...,دکتر مهناز عابدینی متخصص رادیولوژی و سونوگرافی...,دکتر مهناز عابدینی متخصص رادیولوژی و سونوگرافی...,دکتر مهناز عابدینی,آدرس و تلفن دکتر مهناز عابدینی نظرات و تجربیات...,doctor-yab.ir/Search/14773/%D8%AF%DA%A9%D8%AA%...,doctor-yab.ir,175
3,تکنولوژی و کامپبوتر,نرم افزار Geph برای اندروید یک پلت‌فرم چندسکوی...,دانلود تحریم‌گذر Geph برای اندروید خانه/اندروی...,دانلود تحریم‌گذر Geph برای اندروید,دانلود تحریم‌گذر Geph برای اندروید,دانلود نرم افزار Geph,palexe.site/dl/geph-android/,palexe.site,3402
4,تکنولوژی و کامپبوتر,سری جدید تلویزیون‌های هوشمند سامسونگ که با نام...,ترفندهای پرکاربرد تلویزیون‌‌های هوشمند سامسونگ...,ترفندهای پرکاربرد تلویزیون‌‌های هوشمند سامسونگ...,ترفندهای پرکاربرد تلویزیون‌‌های هوشمند سامسونگ,راه‌اندازی تلویزیون همگام‌سازی کنترل اتصال به ...,rokhdadeghtesadi.ir/43874/,rokhdadeghtesadi.ir,3811

In [75]:
test = pd.read_csv("../data/yektanet_test.csv")

In [76]:
train.shape

(4789, 9)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در هنگام کار با داده‌های متنی، پیش‌پردازش داده‌ها به کمک تکنیک‌های پردازش زبان طبیعی یکی از مراحل بسیار تاثیرگذار در یادگیری مدل و عملکرد نهایی است.
در تمرین «کامنت‌کاوی» فصل دسته‌بندی با چندین تکنیک رایج پیش‌پردازش خصوصاً برای زبان فارسی آشنا شدید. در این قسمت نیز می‌توانید تابعی بنویسید که یک رشته (<code>string</code>) را گرفته، اصلاحات موردنظر شما رو روی متن اعمال کرده و در نهایت نتیجه را با فرمت یک رشته (<code>string</code>) خروجی دهد. بررسی و تحلیل کلمات موجود در مجموعه‌داده از نظر تعداد رخداد نیز می‌تواند شما را در پیش‌پردازش بهتر یاری کند.
</font>
</p>

In [77]:
Y = train["category"].copy()

In [78]:
# To-Do
from hazm import stopwords_list
stp_words = stopwords_list()
train["domain"].fillna(train["url"],inplace=True)
test["domain"].fillna(train["url"],inplace=True)

txt_clm_name = ["description","text_content","title","h1","h2"]
for name in txt_clm_name:
    train[name].fillna(" ",inplace=True)
    test[name].fillna(" ",inplace=True)

    
train["texts"] = train["description"] + ' '+ train["text_content"]+ ' '+ train["title"]+ ' '+ train["h1"]+ ' '+ train["h2"]
test["texts"] = test["description"] + ' '+ test["text_content"]+ ' '+ test["title"]+ ' '+ test["h1"]+ ' '+ test["h2"]

In [79]:
train.drop(columns=['description', 'text_content', 'title', 'h1', 'h2', 'url','id'],inplace=True)
test.drop(columns=['description', 'text_content', 'title', 'h1', 'h2', 'url','id'],inplace=True)

In [80]:
from sklearn.preprocessing import OrdinalEncoder
np.random.seed(34)
ord_encoder = OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=np.random.randint(850,900))

ord_encoder.fit(train["domain"].to_numpy().reshape(-1,1))

train["domain"] = ord_encoder.transform(train["domain"].to_numpy().reshape(-1,1))
test["domain"] = ord_encoder.transform(test["domain"].to_numpy().reshape(-1,1))

In [81]:
test

     domain                                              texts
0      16.0  پیام ناشناس یک ابزار رایگان برای ساخت چالش های...
1     213.0  اقتصادنیوز: سید امیر احمد علیه السلام ملقب به ...
2      29.0  آخرین خبر های بین المللی و آخرین تحولات جهان، ...
3     104.0  آهنگ گاهی دریدن لازم نیست با صدای امیر تتلو با...
4     401.0  کیهان با اشاره به حوادث و ناآرامیهای اخیر کشور...
..      ...                                                ...
412   193.0  نوبت دهی دکتر حسین کرمی متخصص جراح کلیه و مجار...
413   193.0  نوبت دهی دکتر مینا اسلام دوست متخصص چشم پزشک د...
414   883.0  دانلود فول آلبوم افسر شهیدی شامل با کیفیت 320 ...
415   523.0  عکس حیوانات زیبا و بامزه برای پروفایل ، عکس حی...
416   883.0  برای بررسی قیمت و مشخصات فنی لپ تاپ HP Pavilio...

[417 rows x 2 columns]

In [82]:
train["#content"] = train.groupby("domain").count().loc[train["domain"]]["texts"].to_numpy()
test["#content"] = test.groupby("domain").count().loc[test["domain"]]["texts"].to_numpy()

In [83]:
train

,category,domain,texts,#content
0,کتاب و ادبیات,356.0,"از شوبنده ها: جستجو معنی ""از شوبنده ها"" در فره...",7
1,تجارت و اقتصاد,372.0,بیت‌کوین کش یک ارز مجازی مشهور است و بیت‌کوین ...,4
2,سلامت,193.0,نوبت دهی دکتر مهناز عابدینی متخصص رادیولوژی و ...,242
3,تکنولوژی و کامپبوتر,566.0,نرم افزار Geph برای اندروید یک پلت‌فرم چندسکوی...,2
4,تکنولوژی و کامپبوتر,633.0,سری جدید تلویزیون‌های هوشمند سامسونگ که با نام...,2
...,...,...,...,...
4784,سلامت,558.0,سلام خانم دکتر یه سوال مهم دارم آیا قرص ال دی ...,2
4785,خانه و باغبانی,280.0,فروش نقدی و اقساطی ماشین لباسشویی اسنوا سری ها...,8
4786,غذا و نوشیدنی,604.0,قهوه سرا در مشهد -شماره تلفن قهوه سرا در مشهد ...,28
4787,ورزش,299.0,گزارش برخی رسانه‌های خارجی نشان می‌دهد اطلاعات...,42
4788,تکنولوژی و کامپبوتر,200.0,دانلود برنامه جدید برای به روزرسانی درایورهای ...,4

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در هنگام تعبیه‌سازی به کمک کتابخانه‌ی <code>scikit-learn</code>
از آنجا که ممکن است توکن‌ساز (Tokenizer) مورد استفاده در این کتابخانه مناسب زبان فارسی نباشد، بهتر است از توکن‌سازهای مناسب این زبان استفاده کنیم. کافیست تابعی بنویسید که یک رشته (<code>string</code>) را گرفته و به کمک کتابخانه‌ی موردنظر شما (مثل <code>word_tokenize</code> در کتابخانه‌ی هضم) توکن‌های آن را جدا کند. خروجی تابع لیستی از توکن‌ها خواهد بود.
</font>
</p>

In [50]:
from hazm import WordTokenizer
def tokenizer(text):
    w_tokenizer = WordTokenizer()
    
    return w_tokenizer.tokenize(text)

In [51]:
# s = "به یک تمرین صنعتی از کاربرد یادگیری ماشین در پردازش زبان طبیعی (NLP) خوش آمدید. در این تمرین داده‌های واقعی وب فارسی که توسط پلتفرم یکتانت پالایش و جمع‌آوری شده در اختیار ما قرار گرفته است."
texts = train["texts"][0:20].apply(lambda s: tokenizer(s))
texts

0     [از, شوبنده, ها, :, جستجو, معنی, ", از, شوبنده...
1     [بیت‌کوین, کش, یک, ارز, مجازی, مشهور, است, و, ...
2     [نوبت, دهی, دکتر, مهناز, عابدینی, متخصص, رادیو...
3     [نرم, افزار, Geph, برای, اندروید, یک, پلت‌فرم,...
4     [سری, جدید, تلویزیون‌های, هوشمند, سامسونگ, که,...
5     [شنیدن, و, دانلود, رایگان, تلفظ, کلمه, ی, غم, ...
6     [مهر, نوشت, :, دیدار, تیم‌های, فوتبال, پورتو, ...
7     [اطلاعات, ،, نظرات, ،, منو, و, قیمت, ،, آدرس, ...
8     [جان, کربی, گفت, :, برای, اجرای, مجدد, توافق, ...
9     [انواع, دستور, پخت, غذا, ،, دسر, ،, سالاد, به,...
10    [رئیس, شورای, اسلامی, شهر, سامان, گفت, :, بیژن...
11    [⬅️, ۱۳۲, متراستاندارد\r, ⬅️, ۳, خواب, خوش, نق...
12    [خواص, روغن, سبوس, برنج, ،, طرز, تهیه, و, نحوه...
13    [مقایسه, خودروها, از, 90, تا, 15000, میلیون, ت...
14    [پرسشکده, :, مرجع, پرسش, و, پاسخ, فارسی, ایران...
15    [بدون, برند,تیغه, استیل,سایز, ۴, ٫, ۵, ,بله, خ...
16    [هزاران, آگهی, خرید, و, فروش, آپارتمان, ،, خان...
17    [کرج-, رئیس, پلیس, آگاهی, البرز, گفت, :, کینه‌...
18    [پلیس, در, خیابان, دماوند, به, یک, سارق, شلیک,...
19    [تهران-, خسرو, معتضد, با, اشاره, به, اظهارنظر,...
Name: texts, dtype: object

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

# vectorizer = CountVectorizer(input = 'content',lowercase=False ,tokenizer=lambda x: x ,analyzer='word' , stop_words=stp_words)
vectorizer = CountVectorizer(analyzer='word' , stop_words=stp_words)

# vectorizer.fit(texts)

# sample = vectorizer.transform(texts)
# sample

vectorizer.fit(train["texts"])

count_vect = vectorizer.transform(train["texts"])
count_vect_t = vectorizer.transform(test["texts"])
count_vect.toarray()

/opt/anaconda3/envs/qenv/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:409: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['آید', 'توان', 'تواند', 'توانند', 'رسد', 'رود', 'سال', 'نمی', 'های', 'گوید', 'گویند'] not in stop_words.
  warnings.warn(

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [84]:
from sklearn.feature_extraction.text import TfidfVectorizer


# vectorizer = CountVectorizer(input = 'content',lowercase=False ,tokenizer=lambda x: x ,analyzer='word' , stop_words=stp_words)
vectorizer = TfidfVectorizer(analyzer='word' , stop_words=stp_words)

# vectorizer.fit(texts)

# sample = vectorizer.transform(texts)
# sample

vectorizer.fit(train["texts"])

tfidf_vect = vectorizer.transform(train["texts"])
tfidf_vect_t = vectorizer.transform(test["texts"])
tfidf_vect

/opt/anaconda3/envs/qenv/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:409: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['آید', 'توان', 'تواند', 'توانند', 'رسد', 'رود', 'سال', 'نمی', 'های', 'گوید', 'گویند'] not in stop_words.
  warnings.warn(

<4789x118261 sparse matrix of type '<class 'numpy.float64'>'
	with 1331939 stored elements in Compressed Sparse Row format>

In [71]:
from sklearn.decomposition import PCA
pca = PCA(n_components=21)
pca.fit(tfidf_vect.toarray())
transformed_text = pca.transform(tfidf_vect.toarray())
transformed_text_t = pca.transform(tfidf_vect_t.toarray())

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
توجه داشته باشید انتخاب این‌که از کدام ویژگی‌ها (متن‌ها) به‌عنوان ورودی الگوریتم استفاده کنید بر عهده‌ی خودتان است. می‌توانید تنها از یک ستون مثل <code>title</code> استفاده کنید یا می‌توانید به‌نحوی متن یا حتی بردار ویژگی هر ستون را با همدیگر ترکیب کنید. همچنین فراموش نکنید که ستون متغیر هدف یعنی <code>category</code> نیاز به کدگذاری دارد.
</font>
</p>

In [85]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
target = encoder.fit_transform(train["category"])
Y = encoder.transform(Y)
train.drop(columns=["category"],inplace=True)

In [56]:
# from imblearn.over_sampling import SMOTE
# # from imblearn.over_sampling import RandomOverSampler

# # ros = RandomOverSampler(sampling_strategy={'average': 57000, 'very expensive': 57000})
# # X_resampled, y_resampled = ros.fit_resample(transformed_text, target)

# sm = SMOTE(sampling_strategy='minority', k_neighbors=4, random_state=42)
# transformed_text, target = sm.fit_resample(transformed_text, target)

In [72]:
pd.DataFrame(target).value_counts()

11    549
20    464
5     446
19    371
18    275
4     263
2     250
14    222
9     212
0     189
10    158
13    151
16    141
17    119
7     116
15    108
21     79
3      66
1      42
8      33
12     31
6      25
dtype: int64

In [86]:
from sklearn.model_selection import train_test_split
df, validatin_text, target, validation_target = train_test_split(transformed_text,target , test_size=0.1)

In [66]:
validation_target.shape

(479,)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
اکنون وقت آن رسیده که الگوریتم یادگیری ماشین موردنظر خود را بر روی داده‌های آموزشی اجرا کنید. در انتخاب الگوریتم کاملاً آزاد هستید. برای این بخش می‌توانید ابتدا هر ورودی متن را به کمک تکنیک‌های معرفی‌شده در درسنامه‌های این فصل (مثل Bag-of-Word یا Tf-idf) به بردارهای ویژگی عددی تبدیل کنید. سپس این بردارها را همراه با لیست برچسب‌های صحیح به الگوریتم بدهید تا مدل آموخته شود. علاوه بر این می‌توانید تمام این مراحل را در یک خط لوله‌ (<code>Pipeline</code>) نیز تعریف کنید.
</font>
</p>

In [87]:
# To-Do
from sklearn.svm import SVC
model = SVC(C = 35,class_weight='balanced')
model.fit(df,target)
model.score(df,target)

0.8475638051044083

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>F1-score</code> نام دارد و از رویکرد میانگین‌گیری وزن‌دار (<code dir=ltr>average='weighted'</code>) استفاده می‌شود.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه‌ی آموزش یا اعتبارسنجی ارزیابی کنید و طبق نتایج به‌دست‌آمده پارامترهای مدل خود را بهتر تنظیم کنید.
</font>
</p>

In [88]:
from sklearn.metrics import f1_score
score = f1_score(validation_target,model.predict(validatin_text),average='weighted')
score

0.7522156168245318

In [89]:
train["texts"] = pd.DataFrame(model.predict(transformed_text))
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4789 entries, 0 to 4788
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   domain    4789 non-null   float64
 1   texts     4789 non-null   int64
 2   #content  4789 non-null   int64
dtypes: float64(1), int64(2)
memory usage: 112.4 KB

In [90]:
from sklearn.ensemble import GradientBoostingClassifier
xgb = GradientBoostingClassifier(n_estimators=100)
xgb.fit(train,Y)

GradientBoostingClassifier()

In [91]:
from sklearn.metrics import f1_score
score = f1_score(Y,xgb.predict(train),average='weighted')
score

0.8764620940099221

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدل‌سازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در مجموعه‌ی آزمون استفاده کنید و نتایج را در یک دیتافریم تک‌ستونه با نام <code>submission</code> و در قالب زیر آماده کنید. توجه داشته باشید که ترتیب پیش‌بینی شما اهمیت دارد یعنی به عنوان مثال پیش‌بینی مدل برای نمونه‌ی آزمون <code>m</code> ام را باید در ردیف <code>m</code> ام این دیتافریم ذخیره کنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>category</code>|پیش‌بینی مدل شما (از جنس رشته)|
    
</font>
</div>
</center>

In [92]:
test["texts"] = pd.DataFrame(model.predict(transformed_text_t))

submission = pd.DataFrame(encoder.inverse_transform(xgb.predict(test)),columns=["category"])
submission

                category
0           هنر و سرگرمی
1    حقوق و دولت و سیاست
2    حقوق و دولت و سیاست
3                 موسیقی
4                اجتماعی
..                   ...
412                سلامت
413                سلامت
414               موسیقی
415         هنر و سرگرمی
416  تکنولوژی و کامپبوتر

[417 rows x 1 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [94]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
file_names = ['text_categorization.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['text_categorization.ipynb', 'submission.csv']

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
💭 اضافه: ابرِ کلمات (Word Cloud)
</font>
</h2>

<center>
<img src="wordcloud.png">
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
یکی از کتابخانه‌های بسیار جالب مرتبط با متن در پایتون، <a href="https://github.com/amueller/word_cloud"><code>WordCloud</code></a> نام دارد. این کتابخانه به شما کمک می‌کند تا ابری از پرتکرارترین توکن‌های موجود در یک مجموعه‌متن را به شکلی زیبا به تصویر بکشید. خوشبختانه نسخه‌ی فارسی این کتابخانه نیز وجود دارد که می‌توانید از <a href="https://github.com/alihoseiny/word_cloud_fa">این لینک</a> به صفحه‌ی گیت‌هاب آن مراجعه کنید. حتی می‌توانید به‌صورت دلخواه تصویری را تعیین کنید تا نمایش نهایی توکن‌ها تداعی‌کننده‌ی تصویر موردنظر شما باشد.
</font>
</p>

In [ ]:
cloud_text = ''
# pd.read_csv("../data/yektanet_train.csv")["text_content"]
for text in pd.read_csv("../data/yektanet_train.csv")["text_content"]:
    cloud_text += text + ' '
cloud_text

In [107]:
from wordcloud_fa import WordCloudFa

wc = WordCloudFa(width=1200, height=800, persian_normalize=True, include_numbers=False, max_words=120, background_color='white', min_font_size=10, max_font_size=100)
word_cloud = wc.generate(cloud_text)
image = word_cloud.to_image()
image.show()
image.save('wordcloud.png')

AttributeError: 'ImageDraw' object has no attribute 'textsize'

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>راهنمایی</b>
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ۱. از تکنیک n-gram کمک بگیرید.
    <br>
    ۲. توازن مجموعه‌داده را بررسی کنید.
    <br>
    ۳. در پیش‌پردازش خود می‌توانید حذف حروف اضافه و اعداد، حذف کلمات توقف، نرمال‌سازی و... را آزمایش کنید.
</font>
</p>