<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
تشخیص جنسیت
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    امروزه شبکه‌های اجتماعی کاربردهای گسترده‌ای دارند. اولین استفاده آن، تفریح و اوقات فراغت است. اما از دید دیگر، می‌توان از شبکه‌های اجتماعی برای پیدا کردن الگوهای رفتاری استفاده کرد. به عنوان مثال با تحلیل نظرات کاربران شبکه‌های اجتماعی می‌توانیم ضعف‌های کسب و کار خود را پیدا کنیم.
    <br>
    جنسیت یکی از پارامترهای تاثیرگذار در رفتار کاربران است. در مواجه با یک موضوع، بانوان عمدتا یک‌طور واکنش نشان خواهند داد و آقایان نیز طور دیگری!
    <br>
    حال در این تمرین قصد داریم با اطلاعاتی که دیتاک از کاربران توییتر و اینستاگرم در اختیار ما قرار داده است، جنسیت آن‌ها را پیش‌بینی کنیم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [1]:
import numpy as np
import pandas as pd

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
مجموعه داده آموزش ۸۰۰۰ سطر و ۱۰ ستون دارد. در جدول زیر، اطلاعات بیشتری در مورد داده نوشته شده است.     
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|gender|جنسیت (ستون هدف)|
|age|بازه سنی کاربر|
|fullname|نامی که در پروفایل شبکه اجتماعی نوشته شده است |
|username|نام کاربری|
|biography|بیوگرافی شبکه اجتماعی کاربر|
|follower_count|تعداد دنبال‌کننده‌های کاربر|
|following_count|تعداد افرادی که کاربر را دنبال می‌کنند|
|is_business|کسب‌وکاری بودن حساب کاربری|
|is_verified|تایید شده بودن حساب کاربری|
|is_private|خصوصی بودن حساب کاربری|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ستون <code>age</code> متغیر پیوسته نیست؛ بلکه دسته‌های سنی را نشان می‌دهد. در جدول زیر نحوه نگاشت سن را مشاهده می‌کنیم.
</font>
</p>


<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|سن واقعی کاربران|عدد نگاشت شده|
|:------:|:---:|
|1|کمتر از ۱۸ سال|
|2|از ۱۹ تا ۲۹ سال|
|3|از ۳۰ تا ۴۰ سال|
|4|بالاتر از ۴۰ سال|
    
</font>
</div>
</center>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>train_data.csv</code> و نمونه‌های آزمون که باید دسته‌ی آن‌ها را پیش‌بینی کنید در فایل <code>test_data.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از دادگان آموزشی را به عنوان دادگان اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [293]:
validation_index = np.random.randint(1,8000,800)

In [343]:
train = pd.read_csv('../data/train_data.csv')
test = pd.read_csv('../data/test_data.csv')
train

,gender,age,fullname,username,biography,follower_count,following_count,is_business,is_verified,is_private
0,man,2,Farshid,mr_gh_farshid,دردا ک در این بادیه بسیار دویدیم...\nGlory man...,1604.0,1407.0,0.0,0.0,0.0
1,woman,2,zahr@72,zahra.roozbahani72,"خواهی که زکوچ در امان برگردی\nباید که به جان ,...",67.0,501.0,0.0,0.0,0.0
2,woman,2,ms farahnaz♥,___lady.farahnazi.__,"Having you, is all I wish for \nداشتنت، تمامِ...",0.0,0.0,0.0,0.0,0.0
3,woman,1,Lena.mommy farzan,mommy.lena3361,دردونه من لنا کوچولو,0.0,0.0,0.0,0.0,0.0
4,woman,2,Narsis Asadollahi,_l.aurora.l_,I am an animation student\n🎧🎼🎨⚓️🤍 \n@general.m...,200.0,328.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
7995,woman,2,Ŋεgɨŋ,negiiin_bahrmandi,﷽\nAllah IS Enough FoR Me?\n♥️?,0.0,0.0,0.0,0.0,0.0
7996,man,3,h🗯abdi🗯offìcial,h.abdi.official,حقوقی,0.0,0.0,1.0,0.0,0.0
7997,woman,2,⚜رویا احمدی⚜,roya.ahmadi.k,مهندس صنایع👩‍🔧🏭 Industrial engineer\nمعمار👩‍💻👷...,1260.0,1167.0,0.0,0.0,0.0
7998,man,3,لرستان &خرم اباد,erfanpouersif,khoramabad,0.0,0.0,0.0,0.0,0.0
7999,man,4,Sasan,sasan.zeinoddin,Sport 🏃🏻‍♂️🏊🏼‍♂️🚴🏽‍♂️\nCivil Engineer🗽\nKurdis...,0.0,0.0,0.0,0.0,0.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

In [344]:
# do some preprocessing :)
train.fillna(0,inplace=True)
train["follower_count_cat"] = pd.cut(train["follower_count"],bins=[0,50,100,150,200,400,600,1000,850000],labels=[0,1,2,3,4,5,6,7],include_lowest=True).astype("int")
train["following_count_cat"] = pd.cut(train["following_count"],bins=[0,50,100,150,200,400,600,800,1000,8000],labels=[0,1,2,3,4,5,6,7,8],include_lowest=True).astype("int")

test.fillna(0,inplace=True)
test["follower_count_cat"] = pd.cut(test["follower_count"],bins=[0,50,100,150,200,400,600,1000,850000],labels=[0,1,2,3,4,5,6,7],include_lowest=True).astype("int")
test["following_count_cat"] = pd.cut(test["following_count"],bins=[0,50,100,150,200,400,600,800,1000,8000],labels=[0,1,2,3,4,5,6,7,8],include_lowest=True).astype("int")

/opt/anaconda3/envs/qenv/lib/python3.9/site-packages/pandas/core/arrays/categorical.py:528: RuntimeWarning: invalid value encountered in cast
  fill_value = lib.item_from_zerodim(np.array(np.nan).astype(dtype))

In [345]:
train["biography"] = train["fullname"] + " "+ train["username"] + train["biography"]
test["biography"] = test["fullname"] + " "+ test["username"] + test["biography"]

In [346]:
from emoji import emoji_count
train["#emoji"] = train["biography"].apply(lambda x: emoji_count(x))
test["#emoji"] = test["biography"].apply(lambda x: emoji_count(x))

In [347]:
from hazm import stopwords_list
from stop_words import get_stop_words

stp_ls_en = get_stop_words('english')
stp_ls_fa = stopwords_list()
stp_ls = stp_ls_en + stp_ls_fa

In [348]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA


count_vector = CountVectorizer(lowercase=True,stop_words=stp_ls)
count_vector.fit(train["biography"])
bio_vector = count_vector.transform(train["biography"])
bio_vector_t = count_vector.transform(test["biography"])

print(bio_vector.get_shape())

decom_Pca = PCA(n_components=25)
decom_Pca.fit(bio_vector.toarray())
decomposed_bio = pd.DataFrame(decom_Pca.transform(bio_vector.toarray())
                              ,columns=["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24"])
decomposed_bio_t = pd.DataFrame(decom_Pca.transform(bio_vector_t.toarray())
                                ,columns=["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24"])

/opt/anaconda3/envs/qenv/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:409: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['aren', 'can', 'couldn', 'didn', 'doesn', 'don', 'hadn', 'hasn', 'haven', 'isn', 'let', 'll', 'mustn', 're', 'shan', 'shouldn', 've', 'wasn', 'weren', 'won', 'wouldn', 'آید', 'توان', 'تواند', 'توانند', 'رسد', 'رود', 'سال', 'نمی', 'های', 'گوید', 'گویند'] not in stop_words.
  warnings.warn(

(8000, 35262)

In [349]:
decomposed_bio

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,-0.037214,-0.008867,-0.041172,-0.083269,-0.008850,-0.028383,-0.026935,-0.054232,-0.032460,-0.004187,...,0.011667,-0.053456,0.037363,0.024165,-0.026667,0.000735,-0.010451,-0.055380,0.011395,0.013746
1,-0.073298,0.030539,-0.031576,-0.102481,-0.059046,-0.021853,-0.034452,-0.027261,0.037314,0.002135,...,-0.081379,0.010967,-0.053233,0.071820,-0.021297,0.048972,-0.075868,-0.073493,0.115181,-0.089784
2,-0.091974,0.044530,-0.029806,-0.054625,-0.048019,-0.038538,-0.020000,-0.009803,0.068877,0.019417,...,0.028863,-0.035363,-0.036923,-0.005388,-0.040793,0.001439,0.000316,-0.089652,0.079178,-0.065020
3,-0.054604,-0.008318,-0.022771,-0.081840,-0.005531,-0.024540,-0.024546,-0.033287,-0.035290,0.001976,...,0.012414,-0.024764,0.012373,0.011606,-0.031442,-0.022451,0.010822,-0.025057,0.026581,-0.006556
4,-0.022478,-0.066921,-0.042925,-0.084801,-0.012935,-0.035986,0.005608,0.032901,-0.079346,-0.046544,...,-0.021901,-0.018702,-0.024660,0.038871,0.077468,-0.106663,-0.076482,0.108173,0.039581,0.125969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,-0.043542,0.002868,-0.018116,-0.086375,-0.006769,-0.028179,-0.023299,-0.035477,-0.032607,-0.018533,...,0.008467,-0.032140,0.016920,0.013955,-0.016711,-0.003771,0.007157,-0.019984,0.013760,0.005881
7996,-0.058368,0.002274,-0.025791,-0.085217,-0.006389,-0.029346,-0.021082,-0.028843,-0.033744,-0.012875,...,0.015397,-0.029076,0.011201,0.013611,-0.023512,-0.020052,0.011684,-0.029093,0.027869,-0.009036
7997,-0.004239,-0.183942,-0.115240,-0.033364,0.291533,0.920891,-0.090742,-0.255752,0.274229,-0.178409,...,0.055448,-0.092388,0.068872,-0.057819,0.106528,-0.232966,-0.013061,0.217560,-0.086775,-0.200531
7998,-0.058080,0.002533,-0.025224,-0.083051,-0.006979,-0.030063,-0.021597,-0.028198,-0.032981,-0.021099,...,0.014653,-0.029128,0.009190,0.012878,-0.021751,-0.016783,0.014896,-0.026743,0.023170,-0.007155
7999,0.049224,-0.191177,-0.082605,-0.077417,0.234643,0.959551,-0.038236,-0.292260,0.279608,-0.176960,...,0.082896,-0.041472,-0.004097,-0.032989,-0.057182,-0.022887,0.045267,-0.011927,0.035114,0.009543

In [350]:
target = train["gender"].replace({"man": 0, "woman": 1})
train.drop(columns=["gender","fullname","username", "biography"],inplace=True) # "follower_count","following_count"
test.drop(columns=["fullname","username", "biography"],inplace=True)

In [351]:
df = train.join(decomposed_bio)
test_df = test.join(decomposed_bio_t)

In [352]:
train

,age,follower_count,following_count,is_business,is_verified,is_private,follower_count_cat,following_count_cat,#emoji
0,2,1604.0,1407.0,0.0,0.0,0.0,7,8,3
1,2,67.0,501.0,0.0,0.0,0.0,1,5,0
2,2,0.0,0.0,0.0,0.0,0.0,0,0,9
3,1,0.0,0.0,0.0,0.0,0.0,0,0,0
4,2,200.0,328.0,0.0,0.0,0.0,3,4,5
...,...,...,...,...,...,...,...,...,...
7995,2,0.0,0.0,0.0,0.0,0.0,0,0,1
7996,3,0.0,0.0,1.0,0.0,0.0,0,0,2
7997,2,1260.0,1167.0,0.0,0.0,0.0,7,8,17
7998,3,0.0,0.0,0.0,0.0,0.0,0,0,0
7999,4,0.0,0.0,0.0,0.0,0.0,0,0,6

In [353]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# df = pd.DataFrame(scaler.fit_transform(df))
# df

In [354]:
validation_target = target[validation_index]
target = target.drop(validation_index)

In [355]:
validation_data = df.iloc[validation_index]
df = df.drop(validation_index)

In [356]:
df

,age,follower_count,following_count,is_business,is_verified,is_private,follower_count_cat,following_count_cat,#emoji,0,...,15,16,17,18,19,20,21,22,23,24
0,2,1604.0,1407.0,0.0,0.0,0.0,7,8,3,-0.037214,...,0.011667,-0.053456,0.037363,0.024165,-0.026667,0.000735,-0.010451,-0.055380,0.011395,0.013746
1,2,67.0,501.0,0.0,0.0,0.0,1,5,0,-0.073298,...,-0.081379,0.010967,-0.053233,0.071820,-0.021297,0.048972,-0.075868,-0.073493,0.115181,-0.089784
2,2,0.0,0.0,0.0,0.0,0.0,0,0,9,-0.091974,...,0.028863,-0.035363,-0.036923,-0.005388,-0.040793,0.001439,0.000316,-0.089652,0.079178,-0.065020
3,1,0.0,0.0,0.0,0.0,0.0,0,0,0,-0.054604,...,0.012414,-0.024764,0.012373,0.011606,-0.031442,-0.022451,0.010822,-0.025057,0.026581,-0.006556
4,2,200.0,328.0,0.0,0.0,0.0,3,4,5,-0.022478,...,-0.021901,-0.018702,-0.024660,0.038871,0.077468,-0.106663,-0.076482,0.108173,0.039581,0.125969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,2,0.0,0.0,0.0,0.0,0.0,0,0,1,-0.043542,...,0.008467,-0.032140,0.016920,0.013955,-0.016711,-0.003771,0.007157,-0.019984,0.013760,0.005881
7996,3,0.0,0.0,1.0,0.0,0.0,0,0,2,-0.058368,...,0.015397,-0.029076,0.011201,0.013611,-0.023512,-0.020052,0.011684,-0.029093,0.027869,-0.009036
7997,2,1260.0,1167.0,0.0,0.0,0.0,7,8,17,-0.004239,...,0.055448,-0.092388,0.068872,-0.057819,0.106528,-0.232966,-0.013061,0.217560,-0.086775,-0.200531
7998,3,0.0,0.0,0.0,0.0,0.0,0,0,0,-0.058080,...,0.014653,-0.029128,0.009190,0.012878,-0.021751,-0.016783,0.014896,-0.026743,0.023170,-0.007155
7999,4,0.0,0.0,0.0,0.0,0.0,0,0,6,0.049224,...,0.082896,-0.041472,-0.004097,-0.032989,-0.057182,-0.022887,0.045267,-0.011927,0.035114,0.009543

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
</font>
</p>

In [357]:
# modeling :)
from sklearn.ensemble import GradientBoostingClassifier
xgb = GradientBoostingClassifier(learning_rate=0.1)
xgb.fit(df,target)

GradientBoostingClassifier()

In [358]:
from sklearn.svm import SVC
model = SVC(C= 10)
model.fit(df,target)

SVC(C=10)

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>f1_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی دادگان آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

In [359]:
# evaluate model :)
from sklearn.metrics import f1_score
score_xgb = f1_score(validation_target , xgb.predict(validation_data))
score = f1_score(validation_target , model.predict(validation_data))

( score_xgb , score)

(0.7674418604651162, 0.6713008937437934)

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>75%</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدلسازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در داده تست استفاده کنید و نتایج را در قالب جدول (<code>dataframe</code>) زیر آماده کنید.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|gender|جنسیت کاربر|
    
</font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    اسم دیتافریم باید <i>submission</i> باشد؛ در غیر این صورت، سامانه داوری نمی‌تواند تلاش‌ شما را ارزیابی کند.
    <br>
    این دیتافریم تنها شامل ۱ ستون با اسم <i>gender</i> است و ۲۰۰۰ سطر دارد.
    <br>
    به ازای هر سطر موجود در دیتافریم <i>test_data</i> شما باید یک مقدار پیشبینی شده داشته باشید.
    <br>
    جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته در جواب شما، مقادیر ستون <i>gender</i> ممکن است متفاوت باشد.
</font>
</p>

<div style="text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
||gender|
|----|-----|
|0|woman|
|1|woman|
|2|man|
|3|woman|
|4|man|

</font>
</div>

In [360]:
# predict test samples
submission = pd.DataFrame(xgb.predict(test_df),columns=["gender"]).replace({0: "man", 1: "woman"})
submission

     gender
0     woman
1       man
2     woman
3     woman
4     woman
...     ...
1995  woman
1996  woman
1997    man
1998  woman
1999  woman

[2000 rows x 1 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [361]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
file_names = ['gender_detection.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['gender_detection.ipynb', 'submission.csv']